eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
spring:
  application:
    name: ex-kafka-producer
  kafka:
    producer:
      bootstrap-servers: localhost:29092
