eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: ex-gateway
  cloud: 
    gateway:
      routes:
      - id: ex-worker
        uri: lb://ex-worker
        predicates:
        - Path=/ex-worker/**
      - id: ex-user
        uri: lb://ex-user
        predicates:
        - Path=/ex-user/**